name = 'Typo'
license = 'MIT'
licenselink = 'https://github.com/francoposa/hypo/blob/main/LICENSE'
description = 'A simple Hugo theme - like Typo but with even less'

homepage = 'https://github.com/francoposa/francoposa.io'

demosite = 'https://francoposa.io/'

[author]
name = 'Franco Posa'
homepage = 'https://francoposa.io/'
